# -*- coding: utf-8 -*-
"""esra küçükşen_midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-9tCqwwCPn7okFYhQGpi4p9Odu3ZN16

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox

Describe what an algorithm is.

Algorithm is a designed path to solve a problem or achieve the desired result.

Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]

Brute force is approaching the problem through all of the possible solutions not only the best of most logical ones. That makes it more expensive and not user friendly. It uses even the useless solutions and that is waste of time and energy.

In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice.

In my work practice, which is architecture, we need to keep up with the day. Architecture is basically a field that combine of some parameters which are changing day by day. In that manner a tool is needed that is designed as a path to reach a certain result. This is where algorithmic design helps and this is why it is necessary. Aesthetic is another issue that we need to deal with. Algorithmic design is, again, a nice way to design and represent what is in one's mind.

Create a python dictionary for your name surname and year of birth.
"""

dict_esra = {'name':'esra','surname':'kucuksen','birth':'1995'}
dict ['name']

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if 'name'[0] == 'a':
   print ('my initial is a!')
else:
   print ('my initial is e!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len('surname')%3:
  print ('it is divisible')
else:
  print ('not divisible')

"""Change your year of birth to 2678."""

if 'surname'[0] == 'k':
print ('my year of birth is 2678')

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""